### PR TITLE
Open tab instead of window during extension registration in KeePass.

### PR DESCRIPTION
**Pull request by t0lik**
I was strongly surprised when Chrome closed silently after I entered Kee Authorisation password and clicked Connect button.
After some investigation I found that the extension closes current window after successful connection to KeePass. In this case I have the OneWindow extension installed in Chrome and all windows opened by the extension turn into tabs of single window and exactly this window was closed by the extension.
Solution: replace window opening to tab opening.

Link to OneWindow extension I used: [OneWindow](https://chrome.google.com/webstore/detail/one-window/papnlnnbddhckngcblfljaelgceffobn?utm_source=chrome-app-launcher-info-dialog)

### CODE REVIEW

**Comment by luckyrat** [comment]
Interesting problem! Thanks for the PR.

I particularly wanted this to be in a popup window to help it standout. Maybe a tab will be OK though... and it would allow us to work around the Firefox bug discussed in #33.

I think the same problem would occur with HTTP Auth. Could you take a look at http://tutorial-section-d.keefox.org/part6 and see if that closes your browser and can be fixed with the same change?

I think we might need to change the style of those dialogs if they are now going to be displayed in tabs instead but maybe once I see them it won't be too bad. Could you post a couple of screenshots showing the end result for the SRP and HTTP auth?

**Comment by t0lik** [comment]
> Could you take a look at http://tutorial-section-d.keefox.org/part6 and see if that closes your browser and can be fixed with the same change?

Yes, the same issue. I can try to fix it by using tabs.

**Comment by t0lik** [comment]
default
Either limit the width of both blocks or at least limit the width of combobox. Maybe it should be better to make these two blocks responsive (depending on browser window width either vertixal or horizontal composition).

**Comment by t0lik** [comment]
default
Acceptable. Maybe would be better to make sentence "The website says: KeeFox tutorial sample" on its own separate line.

**Comment by t0lik** [comment]
From now on both SRP and HTTPAuth are created as window but are closed as tabs and not windows. Works perfectly with and without the OneWindow extension.

**Comment by luckyrat** [comment]
Let's go with the switch to tabs anyway because that will fix #39 - something which if common could cause a large number of upgrades from KeeFox to fail next week.

> Acceptable. Maybe would be better to make sentence "The website says: KeeFox tutorial sample" on its own separate line.

I'll leave this as one line for now to keep the amount of work for translators to a minimum but we can consider that tweak in future.

> Either limit the width of both blocks or at least limit the width of combobox. Maybe it should be better to make these two blocks responsive (depending on browser window width either vertical or horizontal composition).

Yeah, maybe limit to about half of the width in your screenshot. Probably not necessary to wrangle the grids/flexboxes to make it responsive at this stage but again, we could look at some improved design in future.

In general I'm happy that the tab approach with a limited width for the SRP panels will be better overall so if you'd like to update the PR to reflect that, I'll try to review and merge it in the next couple of days, before a new beta release on Saturday.

**Comment by t0lik** [comment]
Tabs are acceptable for SRS and not so suitable for NetworkAuth.html.
When you are choosing login from the list you have to see the page for which you are choosing login. This is impossible via tab.
I've researched popups, notifications and panels and haven't found any universal solution (Edge, FF and Chrome) to show dialog over current tab where you can select login from the list. This shoud be a window 
only. It works everywhere.
Credential Management is also still a draft.

**Comment by luckyrat** [comment]
> When you are choosing login from the list you have to see the page for which you are choosing login. This is impossible via tab.

It is possible to switch tabs but I know what you're saying. A window feels more natural to me, although as you say, it is a compromise since really a modal dialog over the current tab is the most suitable UX but sadly not possible with WebExtensions.

Let's agree on tabs for SRP and windows for Network Auth then. Want to update the PR and then I can merge it in within a few hours?

**Comment by t0lik** [comment]
SRP.html as a tab - done! Also pay attention that I turned first authorization block into primary color (in the previous commit) because this block is more important and most used while registering in KeePass.

**Pull request merged**
