### PR TITLE
Russian l10n.

### PR DESCRIPTION
**Pull request by t0lik**
Russian l10n for messages.json.
Added missing data-i18n attribute for 'Port connection delay' option.

### CODE REVIEW

**Comment by t0lik** [comment]
How can we solve this problem?
For instance:
Now:
point_user_to_tutorial_start_install + space + point_user_to_tutorial_start_install + space + point_user_to_tutorial_end_install
Wish:
point_user_to_tutorial_start_install + space + point_user_to_tutorial_start_install + comma + space + point_user_to_tutorial_end_install

Current text combining by joining with spaces is not always suitable for some languages and sentences.
For example, there are some kind of sentences in Russian when two parts of a sentence are divided by comma.

**Comment by luckyrat** [comment]
Thanks for this. We do all translation work via Transifex rather than GitHub though so I can't accept this PR into master (the "source" file of English being the exception to this rule). Thankfully, since this is the first Russian translation it was easy for me to put your translations into Transifex.

From a pending documentation update I'll publish in a day or so:

> The best way for you to get started is to log in (or click the link to sign up) here: https://www.transifex.com/signin/
> 
> Once you're logged in to Transifex you should see an option to join the team for your language in the Kee project: https://www.transifex.com/projects/p/keefox/

Please can you check that the translated strings have been uploaded by me correctly? @miltador, you might be interested in this too.

There are two notable differences from the changes you supplied in the PR:

1. I've not included the portDelay translation since I'm not expecting that to be present in the next release of the addon.
2. The descriptions that you translated can't be included because the purpose of that description field is for me (or other developers creating the initial English string) to describe what the string is used for so that other translators can get more context to help them to supply the correct translation when the English source string might be interpreted in more than one way. That's the normal way that addons are localised so Transifex has replaced your translations with the English equivalents. I think there are other ways for you to offer additional context or comments on specific strings but those are contained only within Transifex and it's not something I have experience of personally.

I'll include these translations in the next Kee release.

I will also look into whether there is a practical way to automate the building of newly submitted translations so that translators can see a preview version of the add-on before I make a beta release containing the new/changed translations.

That might not happen before I do the next beta release though, if at all.

Interestingly, our Transifex history (from KeeFox) has a different record of how to translate "Loading" into Russian. I suppose there are a variety of regional dialects? A previous translation was "Загружаем".

Generally we should discuss translation issues on Transifex but it's worth a quick moment on your question about spaces and commas first. I imagined that in the case where a comma needs to come before the space for a specific language, that comma can be included at the end of the translated string. Although, if the comma must be used instead of a space then that is going to be a bigger discussion topic I think.

**Comment by t0lik** [comment]
I have joined to the project in Transifex.
Tried to translate and save "Loading" string and with no success:
default

**Comment by t0lik** [comment]
At the moment I don't see my translation on the Transifex.

**Comment by t0lik** [comment]
Ooops! My mistake. Now I'm checking translation for Kee.

**Comment by t0lik** [comment]
All the translation strings are revised now. I have corrected some of them,

**Comment by t0lik** [comment]
Also I can't mark translations as reviewed.

**Pull request closed without merging**
